### Get timeslots
GET http://localhost:3001/timeslots

### Get last timeslots per employee
GET http://localhost:3001/timeslots/last

### Generate new timeslots
POST http://localhost:3001/timeslots/new HTTP/1.1
Content-Type: application/json

{
    "employee_id": 1,
    "duration": "60",
    "start_time": "10:00:00",
    "end_time": "16:00:00",
    "start_date": "2024-04-13",
    "end_date": "2024-04-14"
}

### Update a timeslot
PUT http://localhost:3001/timeslots/update/37 HTTP/1.1
Content-Type: application/json

{
    "is_available": false
}


### csutomers

### Get customers
GET http://localhost:3001/customers

### Get a customer
GET http://localhost:3001/customers/1

### add a new customer
POST http://localhost:3001/customers/new HTTP/1.1
Content-Type: application/json

{ 
    "user_account_id" : null,
    "firstname" : "test",
    "lastname" : "test",
    "email" : "test@adbc.com",
    "phone" : "0384740474"
}

### update a customer
PUT http://localhost:3001/customers/update/31 HTTP/1.1
Content-Type: application/json

{ 
    "user_account_id" : null,
    "firstname" : "test2",
    "lastname" : "test2",
    "email" : "test@adbc.com",
    "phone" : "0384740474"
}

### delete a customer
DELETE  http://localhost:3001/customers/delete/28 HTTP/1.1 



### employees

### Get employees
GET http://localhost:3001/employees

### Get an employee
GET http://localhost:3001/employees/20

### add a new employee
POST http://localhost:3001/employees/new HTTP/1.1
Content-Type: application/json

{ 
    "user_account_id" : 22,
    "firstname" : "test",
    "lastname" : "test",
    "email" : "test@ammc.com",
    "phone" : "0384740400",
    "employee_type" : "employee",
    "specialization" : "Pedicure"
}

### update an employee
PUT http://localhost:3001/employees/update/20 HTTP/1.1
Content-Type: application/json

{ 
    "user_account_id" : 22,
    "firstname" : "test_edit",
    "lastname" : "test",
    "email" : "test@ammc.com",
    "phone" : "0384740400",
    "employee_type" : "regular",
    "specialization" : "Pedicure",
    "is_active": false
}

### delete an employee
DELETE  http://localhost:3001/employees/delete/19 HTTP/1.1


### appointments

# get all appointments
GET http://localhost:3001/appointments/all

# get appointments for specific person (username)
GET http://localhost:3001/appointments/all/my/admin

# get more appointment details for a selected appointment
GET http://localhost:3001/appointments/all/my/admin

### update an employee
PUT http://localhost:3001//update/1 HTTP/1.1
Content-Type: application/json

{
    "is_canceled": true
}


### home

# get full name, email, phone and statistics for the home page
GET http://localhost:3001/home/

# update personal info on the home page
PUT http://localhost:3001/employees/update/20 HTTP/1.1
Content-Type: application/json

{ 
    "user_account_id" : 22,
    "firstname" : "test_edit",
    "lastname" : "test",
    "email" : "test@ammc.com",
    "phone" : "0384740400",
    "employee_type" : "regular",
    "specialization" : "Pedicure",
    "is_active": false
}



### users

# register new user (unique username)
POST http://localhost:3001/users/register HTTP/1.1
Content-Type: application/json

{ 
    "username": "user",
    "password": "00000"
}

# login
POST http://localhost:3001/users/login HTTP/1.1
Content-Type: application/json

{ 
    "username": "user",
    "password": "00000"
}